# Generated by Django 3.0 on 2023-08-24 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment5', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
    ]
