# Generated by Django 3.0 on 2023-08-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='is_debut_movie',
            field=models.BooleanField(default=False),
        ),
    ]
