# Generated by Django 3.0 on 2023-08-23 05:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2', '0003_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='assignment2.Gender'),
            preserve_default=False,
        ),
    ]
