# Generated by Django 3.0 on 2023-08-23 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2', '0004_actor_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='gender',
        ),
    ]
