# Generated by Django 3.0 on 2023-08-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2', '0006_actor_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
